version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.11.1
    steps:
      - checkout
      - run:
          name: Run Test
          command: ./gradlew test
workflows:
  test:
    jobs:
      - test
