name: Android CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run all local screenshot tests (Roborazzi)
      id: screenshot
      run: ./gradlew recordRoborazziDebug
    - name: Push new screenshots
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: '*/*.png'
        commit_message: "🤖 Updates screenshots"
    - name: Runscreenshotbot
      run: ./gradlew recordAndVerifyRoborazziDebugScreenshotbotCI
    - name: Run test
      run: ./gradlew testDebug
